version: '3.0'
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=nestjsrealworld-prisma
    ports:
      - 3306:3306
    network_mode: host
  adminer:
    image: adminer
    ports:
      - 8080:8080
    network_mode: host
  app:
    build: .
    ports:
      - 3000:3000
    network_mode: host
    depends_on:
      - db
    entrypoint: /bin/sh
    command: -c "npm run start:prod"
    tty: true
